[lib]
crate-type = [ "staticlib" ]

[package]
name = "stdlib"
version = "0.1.0"
edition = "2021"

[build]
target-dir = ".build/test"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
