[package]
name = "backend_llvm"
version = "0.1.0"
edition = "2024"

[dependencies]
inkwell = { workspace = true }
stdlib = { workspace = true }
new_parser = { workspace = true }
lexer = { workspace = true }
