name: Run Tests

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install LLVM and Clang
      run: sudo apt-get install -y llvm llvm-dev clang libclang1 libclang-dev

    - name: Run tests
      run: cargo test --verbose
